local Emotes = {
	{
		Name = "Head Tilt Right",
		AnimationId = "rbxassetid://129355921091360",
		SortOrder = 1,
	},
	{
		Name = "Lean Front",
		AnimationId = "rbxassetid://77178569527893",
		SortOrder = 2,
	},
	{
		Name = "Jump Pose 1",
		AnimationId = "rbxassetid://108230050302890",
		SortOrder = 3,
	},
	{
		Name = "Jump Pose 2",
		AnimationId = "rbxassetid://116980872796214",
		SortOrder = 4,
	},
	{
		Name = "Lying Down Chill",
		AnimationId = "rbxassetid://83343150266909",
		SortOrder = 5,
	},
	{
		Name = "Sit 1",
		AnimationId = "rbxassetid://135017119032075",
		SortOrder = 6,
	},
	{
		Name = "Sit 2",
		AnimationId = "rbxassetid://98369306537104",
		SortOrder = 7,
	},
	{
		Name = "Sit 3",
		AnimationId = "rbxassetid://82372514065190",
		SortOrder = 8,
	},
	{
		Name = "Sit 4",
		AnimationId = "rbxassetid://125077908140569",
		SortOrder = 9,
	},
	{
		Name = "Sit 5",
		AnimationId = "rbxassetid://123786213469821",
		SortOrder = 10,
	},
	{
		Name = "Heart Duo Pose (Left)",
		AnimationId = "rbxassetid://138058534875276",
		SortOrder = 11,
	},
	{
		Name = "Heart Duo Pose (Right)",
		AnimationId = "rbxassetid://132907215329170",
		SortOrder = 12,
	},
	{
		Name = "Eye Gazing [Duo Pose] 1/2",
		AnimationId = "rbxassetid://119466252737639",
		SortOrder = 13,
	},
	{
		Name = "Eye Gazing [Duo Pose] 2/2",
		AnimationId = "rbxassetid://125525463099520",
		SortOrder = 14,
	},
	{
		Name = "Cute Duo Hug 1/2",
		AnimationId = "rbxassetid://97599535313431",
		SortOrder = 15,
	},
	{
		Name = "Cute Duo Hug 2/2",
		AnimationId = "rbxassetid://106172959031579",
		SortOrder = 16,
	},
	{
		Name = "Head On Shoulder Sit 1/2",
		AnimationId = "rbxassetid://83458338738316",
		SortOrder = 17,
	},
	{
		Name = "Head On Shoulder Sit 2/2",
		AnimationId = "rbxassetid://125314912426494",
		SortOrder = 18,
	},
	{
		Name = "Wait ✋ Challenge!",
		AnimationId = "rbxassetid://94046543077512",
		SortOrder = 19,
	},
	{
		Name = "Boneless",
		AnimationId = "rbxassetid://134604674158491",
		SortOrder = 20,
	},
	{
		Name = "Boogie Bomb",
		AnimationId = "rbxassetid://114481255656984",
		SortOrder = 21,
	},
	{
		Name = "Breakdown",
		AnimationId = "rbxassetid://99926075141080",
		SortOrder = 22,
	},
	{
		Name = "Calamity",
		AnimationId = "rbxassetid://88529710841829",
		SortOrder = 23,
	},
	{
		Name = "Click",
		AnimationId = "rbxassetid://76181238736438",
		SortOrder = 24,
	},
	{
		Name = "Crazy Feet",
		AnimationId = "rbxassetid://73527332854144",
		SortOrder = 25,
	},
	{
		Name = "Crackdown",
		AnimationId = "rbxassetid://137426893736270",
		SortOrder = 26,
	},
	{
		Name = "Dab",
		AnimationId = "rbxassetid://94685604599386",
		SortOrder = 27,
	},
	{
		Name = "Pumpernickel",
		AnimationId = "rbxassetid://84110443970501",
		SortOrder = 28,
	},
	{
		Name = "Pop Lock",
		AnimationId = "rbxassetid://83487813213449",
		SortOrder = 29,
	},
	{
		Name = "Default Dance",
		AnimationId = "rbxassetid://112425416222363",
		SortOrder = 30,
	},
	{
		Name = "PonPon",
		AnimationId = "rbxassetid://82719659946668",
		SortOrder = 31,
	},
	{
		Name = "Eagle",
		AnimationId = "rbxassetid://112580789347577",
		SortOrder = 32,
	},
	{
		Name = "Orange Justice",
		AnimationId = "rbxassetid://119807994627454",
		SortOrder = 33,
	},
	{
		Name = "Macarena",
		AnimationId = "rbxassetid://95743479207877",
		SortOrder = 34,
	},
	{
		Name = "Electro Shuffle",
		AnimationId = "rbxassetid://107624676993918",
		SortOrder = 35,
	},
	{
		Name = "Doing Selfie",
		AnimationId = "rbxassetid://88713319759476",
		SortOrder = 36,
	},
	{
		Name = "Electro Swing",
		AnimationId = "rbxassetid://104375367028898",
		SortOrder = 37,
	},
	{
		Name = "Fancy Feet",
		AnimationId = "rbxassetid://107316991189020",
		SortOrder = 38,
	},
	{
		Name = "Flapper",
		AnimationId = "rbxassetid://139115627082492",
		SortOrder = 39,
	},
	{
		Name = "Flippin Incredible",
		AnimationId = "rbxassetid://77162003635023",
		SortOrder = 40,
	},
}

return Emotes
