--!nonstrict
--[[
	GamepassData (ModuleScript)
]]

local Gamepasses = {
	{
		Id = 1336827563,
		Name = "⭐️ VIP",
		Description = "Unlock an exclusive title, a unique outfit, and a custom trail effect to show off your status!",
		Icon = "rbxassetid://88958508200488",
		SortOrder = 1,
	},
	{
		Id = 1435963207,
		Name = "Sprint",
		Description = "Unleash a burst of speed! This pass unlocks the sprint ability, allowing you to dash through Mount Corvo.",
		Icon = "rbxassetid://125390178610381",
		SortOrder = 2,
	},
	{
		Id = 1422645215,
		Name = "Selfie Pack",
		Description = "Capture your favorite moments! Unlocks the Selfie Camera and Selfie Stick tools to take perfect photos of your journey.",
		Icon = "rbxassetid://86445194598025",
		SortOrder = 3,
	},
	{
		Id = 1334560168,
		Name = "Lasso",
		Description = "Trip 'em up! Use this rope to pull other players' legs and cause some chaos.",
		Icon = "rbxassetid://95198600113179",
		SortOrder = 4,
	},
	{
		Id = 1332730049,
		Name = "Vintage Lantern",
		Description = "Set the mood! This vintage lantern lets you customize its light color to your liking.",
		Icon = "rbxassetid://83683326405481",
		SortOrder = 5,
	},
}

return Gamepasses
